### ISSUE TITLE
how to set custom encoding

### ISSUE THREAD

**Issue by Ciki** [riesenia/pohoda#12]
Hi, I'd like to set custom encoding (utf-8). What is the best way to do it?
It's being set on 2 places currently
- https://github.com/riesenia/pohoda/blob/master/src/Pohoda.php#L133
- https://github.com/riesenia/pohoda/blob/master/src/Pohoda/Agenda.php#L76

**Comment by segy** [comment]
Hi

first one is simple - similar to setting the application attribute. But since this is also used in Agenda, I'd suggest a public static property (you can see `Pohoda::$namespaces` are used there). Please set it to `windows-1250` by default for backward compatibility.
