### ISSUE TITLE
Interní doklady

### ISSUE THREAD

**Issue by Alespost** [riesenia/pohoda#19]
Nejde generovat/parsovat interní doklady.

https://www.stormware.cz/xml/schema/version_2/intDoc.xsd

**Comment by segy** [comment]
Vdaka za info. Nevahajte spravit PR s touto funkcionalitou, pokial by sa Vam hodila.

**Comment by Alespost** [comment]
@segy CI padá na věcech, které jsem neupravoval, mám to opravovat?

**Comment by segy** [comment]
Zdravim... update phpstanu. Fixol som veci - spravte prosim este drobne upravy u Vas, nech to prejde. Dakujem

**Comment by Alespost** [comment]
Zdravím, děkuji za info. Už je to v pořádku. PR #20

**Comment by segy** [comment]
Dakujem. Je to dostupne vo verzii 1.6
