### ISSUE TITLE
orderType values?

### ISSUE THREAD

**Issue by krosoftware** [riesenia/pohoda#26]
Hello all
I'm doing export for client and currently, all orders are placed to "Orders received" area.
How to place exported orders to "Invoice" area?
I presume, "ord:orderType" should contain other value than "receivedOrder"?
if yes, which one?
Thank you.

**Comment by segy** [comment]
Hi

for invoice, you have to use `Invoice`, not `Order`. Possible values for `ord:orderType` are listed in `Riesenia\Pohoda\Order\Header::_configureOptions` method.
