### ISSUE TITLE
Float normalizer vrací číslo ve špatném formátu

### ISSUE THREAD

**Issue by thomasdv** [riesenia/pohoda#31]
OptionsResolver.php, metoda _createNormalizer:

```
case 'float':
case 'number':
    return function ($options, $value) {
        return (string) \floatval(\str_replace(',', '.', \strval(\preg_replace('/[^0-9,.-]/', '', (string) $value))));
    };
```

Pokud je vstupní hodnota `$value` float `10.4`, pak normalizer vrací string `"10,4"` s čárkou jako oddělovačem, což nezchroupe import. 

Možná je v kódu zbytečná konverze zpět na float a přetypování na string? Nebylo by řešením následující?
```
return \str_replace(',', '.', \strval(\preg_replace('/[^0-9,.-]/', '', (string) $value)));
```

Nejsem si jistý, jestli by to nemělo vedlejší následky v jiných případech?

Díky.

**Comment by segy** [comment]
Zdravim

toto je vecou nestastneho nastavenia locale pre LC_NUMERIC. Davalo mi zmysel to odstranit, ale vysledok bol takyto: https://github.com/riesenia/pohoda/actions/runs/2575089324

Kludne urob PR, ktory to fixne bez toho, ze by rozbil testy.

**Comment by segy** [comment]
fixnute v 1.16.4
