### ISSUE TITLE
Missing option <inv:storno>cancelDocument</inv:storno>

### ISSUE THREAD

**Issue by N4thyra** [riesenia/pohoda#39]
Hi,

I'm working on a project where I need to include cancelled invoices as well.

Could you add the storno option below to the list of allowed options? I've just hardcoded it in the source code, but if I ever need to upgrade your library, all the changes will be gone.

`<inv:storno>cancelDocument</inv:storno>`

it should go right after

`<inv:invoiceType>issuedInvoice</inv:invoiceType>`

**Comment by N4thyra** [comment]
![image](https://user-images.githubusercontent.com/25825376/191240070-abb7d084-32d7-4f24-95d8-c32a042d5b26.png)

**Comment by segy** [comment]
Zdravim

nie uplne rozumiem poziadavke - podla https://www.stormware.sk/xml/schema/version_2/invoice.xsd je toto element iba pre export (`Příznak „Storno/Stornujícího“ dokladu (pouze pro export).`). A teda pokojne urob PR, ale v pripade komplexnejsej zmeny poprosim vratane testu. 

Vdaka
